package org.semanticwb.model;

import org.semanticwb.SWBPlatform;
import org.semanticwb.platform.SemanticVocabulary;
import org.semanticwb.platform.SemanticClass;
import org.semanticwb.platform.SemanticProperty;
import java.util.Hashtable;
public class SWBVocabulary
{


    //Classes
    public final SemanticClass swb_User;
    public final SemanticClass swb_Calendar;
    public final SemanticClass swbxf_Text;
    public final SemanticClass swb_Community;
    public final SemanticClass swb_PortletSubType;
    public final SemanticClass swb_TemplateRef;
    public final SemanticClass swb_Templateable;
    public final SemanticClass swb_Iconable;
    public final SemanticClass swb_Deleteable;
    public final SemanticClass swbxf_FormViewRef;
    public final SemanticClass swb_Reference;
    public final SemanticClass swb_Roleable;
    public final SemanticClass swb_PFlowRefable;
    public final SemanticClass swb_Sortable;
    public final SemanticClass swb_Traceable;
    public final SemanticClass swb_RoleRefable;
    public final SemanticClass swb_Ruleable;
    public final SemanticClass swbxf_TextArea;
    public final SemanticClass swb_PFlow;
    public final SemanticClass swb_IPFilter;
    public final SemanticClass swb_RuleRefable;
    public final SemanticClass swb_Valueable;
    public final SemanticClass swb_Calendarable;
    public final SemanticClass swb_UserGroup;
    public final SemanticClass swb_PortletRefable;
    public final SemanticClass swb_Permission;
    public final SemanticClass swbxf_DisplayObject;
    public final SemanticClass swb_TemplateRefable;
    public final SemanticClass swbxf_ObjectBehavior;
    public final SemanticClass swb_PFlowRef;
    public final SemanticClass swb_RuleRef;
    public final SemanticClass swbxf_FormView;
    public final SemanticClass swb_Referensable;
    public final SemanticClass swb_Device;
    public final SemanticClass swb_Hiddenable;
    public final SemanticClass swb_Localeable;
    public final SemanticClass swb_Camp;
    public final SemanticClass swb_Dns;
    public final SemanticClass swb_TemplateGroup;
    public final SemanticClass swb_UserRepository;
    public final SemanticClass swb_Portletable;
    public final SemanticClass swb_Template;
    public final SemanticClass swb_Editable;
    public final SemanticClass swb_Role;
    public final SemanticClass swb_Priorityable;
    public final SemanticClass swbxf_HerarquicalNode;
    public final SemanticClass swb_Activeable;
    public final SemanticClass swb_VersionInfo;
    public final SemanticClass swb_Portlet;
    public final SemanticClass swbxf_ResourceParameter;
    public final SemanticClass swb_Descriptiveable;
    public final SemanticClass swb_Versionable;
    public final SemanticClass swb_RoleRef;
    public final SemanticClass swb_XMLable;
    public final SemanticClass swbxf_ObjectAction;
    public final SemanticClass swb_Rule;
    public final SemanticClass swbxf_DisplayProperty;
    public final SemanticClass swb_XMLConfable;
    public final SemanticClass swb_WebPage;
    public final SemanticClass swb_WebPageable;
    public final SemanticClass swb_WebSite;
    public final SemanticClass swb_Language;
    public final SemanticClass swb_PortletRef;
    public final SemanticClass swb_Indexable;
    public final SemanticClass swb_PortletType;
    public final SemanticClass swb_Viewable;



    //Properties
    public final SemanticProperty swb_created;
    public final SemanticProperty swb_usrSecondLastName;
    public final SemanticProperty swb_modifiedBy;
    public final SemanticProperty swb_usrEmail;
    public final SemanticProperty swb_userGroup;
    public final SemanticProperty swb_updated;
    public final SemanticProperty swb_usrFirstName;
    public final SemanticProperty swb_usrLanguage;
    public final SemanticProperty swb_usrPasswordChanged;
    public final SemanticProperty swb_usrLastName;
    public final SemanticProperty swb_active;
    public final SemanticProperty swb_usrLastLogin;
    public final SemanticProperty swb_creator;
    public final SemanticProperty swb_usrLogin;
    public final SemanticProperty swb_usrPassword;
    public final SemanticProperty swb_hasRole;
    public final SemanticProperty swb_usrSecurityQuestion;
    public final SemanticProperty swb_usrSecurityAnswer;
    public final SemanticProperty swb_title;
    public final SemanticProperty swb_xml;
    public final SemanticProperty swb_description;
    public final SemanticProperty swb_hasPSTPortlets;
    public final SemanticProperty swb_PSTType;
    public final SemanticProperty swb_deleted;
    public final SemanticProperty swb_template;
    public final SemanticProperty swb_priority;
    public final SemanticProperty swb_hasTemplate;
    public final SemanticProperty swb_iconClass;
    public final SemanticProperty swb_formMode;
    public final SemanticProperty swb_formView;
    public final SemanticProperty swb_hasPFlowRef;
    public final SemanticProperty swb_index;
    public final SemanticProperty swb_hasRoleRef;
    public final SemanticProperty swb_hasRule;
    public final SemanticProperty swbxf_textAreaRows;
    public final SemanticProperty swbxf_textAreaCols;
    public final SemanticProperty swb_actualVersion;
    public final SemanticProperty swb_lastVersion;
    public final SemanticProperty swb_ipFilterAction;
    public final SemanticProperty swb_ipFilterNumber;
    public final SemanticProperty swb_hasRuleRef;
    public final SemanticProperty swb_value;
    public final SemanticProperty swb_hasCalendar;
    public final SemanticProperty swb_hasGroupedUser;
    public final SemanticProperty swb_hasPortletRef;
    public final SemanticProperty swb_hasObjectAction;
    public final SemanticProperty swb_hasBehavior;
    public final SemanticProperty swb_hasTemplateRef;
    public final SemanticProperty swbxf_displayObject;
    public final SemanticProperty swbxf_behaviorRefreshOnShow;
    public final SemanticProperty swbxf_interface;
    public final SemanticProperty swbxf_behaviorURL;
    public final SemanticProperty swbxf_hasResourceParam;
    public final SemanticProperty swb_pflow;
    public final SemanticProperty swb_rule;
    public final SemanticProperty swb_hasCreateProperty;
    public final SemanticProperty swb_hasViewProperty;
    public final SemanticProperty swb_hasEditProperty;
    public final SemanticProperty swb_hidden;
    public final SemanticProperty swb_language;
    public final SemanticProperty swb_webPage;
    public final SemanticProperty swb_dnsDefault;
    public final SemanticProperty swb_hasGroupedTemplate;
    public final SemanticProperty swb_hasPortlet;
    public final SemanticProperty swb_templateGroup;
    public final SemanticProperty swb_hasPermission;
    public final SemanticProperty swbxf_heClass;
    public final SemanticProperty swb_previousVersion;
    public final SemanticProperty swb_versionLockedBy;
    public final SemanticProperty swb_versionFile;
    public final SemanticProperty swb_versionComment;
    public final SemanticProperty swb_nextVersion;
    public final SemanticProperty swb_versionNumber;
    public final SemanticProperty swb_camp;
    public final SemanticProperty swb_hits;
    public final SemanticProperty swb_indexable;
    public final SemanticProperty swb_portletWindow;
    public final SemanticProperty swb_xmlConf;
    public final SemanticProperty swb_views;
    public final SemanticProperty swb_portletSubType;
    public final SemanticProperty swb_portletType;
    public final SemanticProperty swb_resParamValue;
    public final SemanticProperty swbxf_resParamName;
    public final SemanticProperty swb_role;
    public final SemanticProperty swb_actGroup;
    public final SemanticProperty swb_actionURL;
    public final SemanticProperty swb_propRequired;
    public final SemanticProperty swb_propSelectValues;
    public final SemanticProperty swb_propHidden;
    public final SemanticProperty swb_propGroup;
    public final SemanticProperty swb_propPromptMessage;
    public final SemanticProperty swb_propInvalidMessage;
    public final SemanticProperty swb_formElement;
    public final SemanticProperty swb_propEditable;
    public final SemanticProperty swb_webPageSortName;
    public final SemanticProperty swb_webPageURLType;
    public final SemanticProperty swb_webPageDiskUsage;
    public final SemanticProperty swb_hasWebPageVirtualParent;
    public final SemanticProperty swb_hasWebPageVirtualChild;
    public final SemanticProperty swb_hasWebPageChild;
    public final SemanticProperty swb_webPageURL;
    public final SemanticProperty swb_webPageParent;
    public final SemanticProperty swb_homePage;
    public final SemanticProperty swb_userRepository;
    public final SemanticProperty swb_portlet;
    public final SemanticProperty swb_portletBundle;
    public final SemanticProperty swb_portletCache;
    public final SemanticProperty swb_portletClassName;
    public final SemanticProperty swb_hasPTPortlet;
    public final SemanticProperty swb_portletMode;
    public final SemanticProperty swb_hasPTSubType;


    public SWBVocabulary()
    {

         SemanticVocabulary vocabulary=SWBPlatform.getSemanticMgr().getVocabulary();
        // Classes
        swb_User=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#User");
        swb_Calendar=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Calendar");
        swbxf_Text=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/xforms/ontology#Text");
        swb_Community=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Community");
        swb_PortletSubType=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#PortletSubType");
        swb_TemplateRef=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#TemplateRef");
        swb_Templateable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Templateable");
        swb_Iconable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Iconable");
        swb_Deleteable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Deleteable");
        swbxf_FormViewRef=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/xforms/ontology#FormViewRef");
        swb_Reference=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Reference");
        swb_Roleable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Roleable");
        swb_PFlowRefable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#PFlowRefable");
        swb_Sortable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Sortable");
        swb_Traceable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Traceable");
        swb_RoleRefable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#RoleRefable");
        swb_Ruleable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Ruleable");
        swbxf_TextArea=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/xforms/ontology#TextArea");
        swb_PFlow=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#PFlow");
        swb_IPFilter=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#IPFilter");
        swb_RuleRefable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#RuleRefable");
        swb_Valueable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Valueable");
        swb_Calendarable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Calendarable");
        swb_UserGroup=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#UserGroup");
        swb_PortletRefable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#PortletRefable");
        swb_Permission=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Permission");
        swbxf_DisplayObject=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/xforms/ontology#DisplayObject");
        swb_TemplateRefable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#TemplateRefable");
        swbxf_ObjectBehavior=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/xforms/ontology#ObjectBehavior");
        swb_PFlowRef=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#PFlowRef");
        swb_RuleRef=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#RuleRef");
        swbxf_FormView=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/xforms/ontology#FormView");
        swb_Referensable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Referensable");
        swb_Device=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Device");
        swb_Hiddenable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Hiddenable");
        swb_Localeable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Localeable");
        swb_Camp=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Camp");
        swb_Dns=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Dns");
        swb_TemplateGroup=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#TemplateGroup");
        swb_UserRepository=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#UserRepository");
        swb_Portletable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Portletable");
        swb_Template=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Template");
        swb_Editable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Editable");
        swb_Role=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Role");
        swb_Priorityable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Priorityable");
        swbxf_HerarquicalNode=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/xforms/ontology#HerarquicalNode");
        swb_Activeable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Activeable");
        swb_VersionInfo=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#VersionInfo");
        swb_Portlet=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Portlet");
        swbxf_ResourceParameter=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/xforms/ontology#ResourceParameter");
        swb_Descriptiveable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Descriptiveable");
        swb_Versionable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Versionable");
        swb_RoleRef=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#RoleRef");
        swb_XMLable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#XMLable");
        swbxf_ObjectAction=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/xforms/ontology#ObjectAction");
        swb_Rule=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Rule");
        swbxf_DisplayProperty=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/xforms/ontology#DisplayProperty");
        swb_XMLConfable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#XMLConfable");
        swb_WebPage=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#WebPage");
        swb_WebPageable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#WebPageable");
        swb_WebSite=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#WebSite");
        swb_Language=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Language");
        swb_PortletRef=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#PortletRef");
        swb_Indexable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Indexable");
        swb_PortletType=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#PortletType");
        swb_Viewable=vocabulary.getSemanticClass("http://www.semanticwebbuilder.org/swb4/ontology#Viewable");



        //Properties
        swb_created=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#created");
        swb_usrSecondLastName=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrSecondLastName");
        swb_modifiedBy=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#modifiedBy");
        swb_usrEmail=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrEmail");
        swb_userGroup=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#userGroup");
        swb_updated=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#updated");
        swb_usrFirstName=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrFirstName");
        swb_usrLanguage=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrLanguage");
        swb_usrPasswordChanged=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrPasswordChanged");
        swb_usrLastName=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrLastName");
        swb_active=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#active");
        swb_usrLastLogin=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrLastLogin");
        swb_creator=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#creator");
        swb_usrLogin=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrLogin");
        swb_usrPassword=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrPassword");
        swb_hasRole=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasRole");
        swb_usrSecurityQuestion=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrSecurityQuestion");
        swb_usrSecurityAnswer=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#usrSecurityAnswer");
        swb_title=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#title");
        swb_xml=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#xml");
        swb_description=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#description");
        swb_hasPSTPortlets=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasPSTPortlets");
        swb_PSTType=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#PSTType");
        swb_deleted=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#deleted");
        swb_template=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#template");
        swb_priority=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#priority");
        swb_hasTemplate=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasTemplate");
        swb_iconClass=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#iconClass");
        swb_formMode=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#formMode");
        swb_formView=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#formView");
        swb_hasPFlowRef=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasPFlowRef");
        swb_index=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#index");
        swb_hasRoleRef=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasRoleRef");
        swb_hasRule=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasRule");
        swbxf_textAreaRows=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/xforms/ontology#textAreaRows");
        swbxf_textAreaCols=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/xforms/ontology#textAreaCols");
        swb_actualVersion=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#actualVersion");
        swb_lastVersion=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#lastVersion");
        swb_ipFilterAction=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#ipFilterAction");
        swb_ipFilterNumber=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#ipFilterNumber");
        swb_hasRuleRef=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasRuleRef");
        swb_value=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#value");
        swb_hasCalendar=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasCalendar");
        swb_hasGroupedUser=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasGroupedUser");
        swb_hasPortletRef=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasPortletRef");
        swb_hasObjectAction=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasObjectAction");
        swb_hasBehavior=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasBehavior");
        swb_hasTemplateRef=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasTemplateRef");
        swbxf_displayObject=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/xforms/ontology#displayObject");
        swbxf_behaviorRefreshOnShow=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/xforms/ontology#behaviorRefreshOnShow");
        swbxf_interface=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/xforms/ontology#interface");
        swbxf_behaviorURL=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/xforms/ontology#behaviorURL");
        swbxf_hasResourceParam=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/xforms/ontology#hasResourceParam");
        swb_pflow=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#pflow");
        swb_rule=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#rule");
        swb_hasCreateProperty=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasCreateProperty");
        swb_hasViewProperty=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasViewProperty");
        swb_hasEditProperty=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasEditProperty");
        swb_hidden=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hidden");
        swb_language=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#language");
        swb_webPage=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#webPage");
        swb_dnsDefault=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#dnsDefault");
        swb_hasGroupedTemplate=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasGroupedTemplate");
        swb_hasPortlet=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasPortlet");
        swb_templateGroup=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#templateGroup");
        swb_hasPermission=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasPermission");
        swbxf_heClass=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/xforms/ontology#heClass");
        swb_previousVersion=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#previousVersion");
        swb_versionLockedBy=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#versionLockedBy");
        swb_versionFile=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#versionFile");
        swb_versionComment=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#versionComment");
        swb_nextVersion=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#nextVersion");
        swb_versionNumber=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#versionNumber");
        swb_camp=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#camp");
        swb_hits=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hits");
        swb_indexable=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#indexable");
        swb_portletWindow=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#portletWindow");
        swb_xmlConf=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#xmlConf");
        swb_views=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#views");
        swb_portletSubType=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#portletSubType");
        swb_portletType=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#portletType");
        swb_resParamValue=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#resParamValue");
        swbxf_resParamName=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/xforms/ontology#resParamName");
        swb_role=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#role");
        swb_actGroup=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#actGroup");
        swb_actionURL=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#actionURL");
        swb_propRequired=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#propRequired");
        swb_propSelectValues=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#propSelectValues");
        swb_propHidden=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#propHidden");
        swb_propGroup=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#propGroup");
        swb_propPromptMessage=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#propPromptMessage");
        swb_propInvalidMessage=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#propInvalidMessage");
        swb_formElement=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#formElement");
        swb_propEditable=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#propEditable");
        swb_webPageSortName=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#webPageSortName");
        swb_webPageURLType=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#webPageURLType");
        swb_webPageDiskUsage=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#webPageDiskUsage");
        swb_hasWebPageVirtualParent=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasWebPageVirtualParent");
        swb_hasWebPageVirtualChild=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasWebPageVirtualChild");
        swb_hasWebPageChild=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasWebPageChild");
        swb_webPageURL=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#webPageURL");
        swb_webPageParent=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#webPageParent");
        swb_homePage=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#homePage");
        swb_userRepository=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#userRepository");
        swb_portlet=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#portlet");
        swb_portletBundle=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#portletBundle");
        swb_portletCache=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#portletCache");
        swb_portletClassName=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#portletClassName");
        swb_hasPTPortlet=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasPTPortlet");
        swb_portletMode=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#portletMode");
        swb_hasPTSubType=vocabulary.getSemanticProperty("http://www.semanticwebbuilder.org/swb4/ontology#hasPTSubType");
    }



        //ListUris
              public Hashtable<String,String> listUris()
              {
                     Hashtable<String,String> namespaces=new Hashtable<String, String>();
                 namespaces.put("swbxf","http://www.semanticwebbuilder.org/swb4/xforms/ontology#");
                 namespaces.put("swb","http://www.semanticwebbuilder.org/swb4/ontology#");
                     return namespaces;
              }
}
