package org.semanticwb.model;

import org.semanticwb.SWBPlatform;
import org.semanticwb.platform.SemanticVocabulary;
import org.semanticwb.platform.SemanticClass;
import org.semanticwb.platform.SemanticProperty;
import static org.semanticwb.platform.SemanticVocabulary.URI;

public class SWBVocabulary
{


    //Classes
    public final SemanticClass swb_User;
    public final SemanticClass swb_Calendar;
    public final SemanticClass swb_Community;
    public final SemanticClass swb_PortletSubType;
    public final SemanticClass swb_TemplateRef;
    public final SemanticClass swb_Templateable;
    public final SemanticClass swb_Deleteable;
    public final SemanticClass swb_Reference;
    public final SemanticClass swb_Roleable;
    public final SemanticClass swb_PFlowRefable;
    public final SemanticClass swb_Sortable;
    public final SemanticClass swb_Traceable;
    public final SemanticClass swb_RoleRefable;
    public final SemanticClass swb_Ruleable;
    public final SemanticClass swb_PFlow;
    public final SemanticClass swb_IPFilter;
    public final SemanticClass swb_RuleRefable;
    public final SemanticClass swb_Valueable;
    public final SemanticClass swb_Calendarable;
    public final SemanticClass swb_TextArea;
    public final SemanticClass swb_PortletRefable;
    public final SemanticClass swb_DisplayObject;
    public final SemanticClass swb_Permission;
    public final SemanticClass swb_TemplateRefable;
    public final SemanticClass swb_PFlowRef;
    public final SemanticClass swb_RuleRef;
    public final SemanticClass swb_Referensable;
    public final SemanticClass swb_Device;
    public final SemanticClass swb_Hiddenable;
    public final SemanticClass swb_Groupable;
    public final SemanticClass swb_Localeable;
    public final SemanticClass swb_Camp;
    public final SemanticClass swb_Dns;
    public final SemanticClass swb_TemplateGroup;
    public final SemanticClass swb_UserRepository;
    public final SemanticClass swb_Portletable;
    public final SemanticClass swb_Template;
    public final SemanticClass swb_DisplayProperty;
    public final SemanticClass swb_Role;
    public final SemanticClass swb_Priorityable;
    public final SemanticClass swb_Activeable;
    public final SemanticClass swb_VersionInfo;
    public final SemanticClass swb_ObjectAction;
    public final SemanticClass swb_FormView;
    public final SemanticClass swb_Portlet;
    public final SemanticClass swb_Descriptiveable;
    public final SemanticClass swb_Versionable;
    public final SemanticClass swb_RoleRef;
    public final SemanticClass swb_XMLable;
    public final SemanticClass swb_Rule;
    public final SemanticClass swb_FormViewRef;
    public final SemanticClass swb_XMLConfable;
    public final SemanticClass swb_WebPage;
    public final SemanticClass swb_WebPageable;
    public final SemanticClass swb_WebSite;
    public final SemanticClass swb_ObjectGroup;
    public final SemanticClass swb_Language;
    public final SemanticClass swb_PortletRef;
    public final SemanticClass swb_Indexable;
    public final SemanticClass swb_PortletType;
    public final SemanticClass swb_Text;
    public final SemanticClass swb_Viewable;



    //Properties
    public final SemanticProperty created;
    public final SemanticProperty usrSecondLastName;
    public final SemanticProperty modifiedBy;
    public final SemanticProperty usrEmail;
    public final SemanticProperty updated;
    public final SemanticProperty usrFirstName;
    public final SemanticProperty usrLanguage;
    public final SemanticProperty usrPasswordChanged;
    public final SemanticProperty usrLastName;
    public final SemanticProperty hasGroup;
    public final SemanticProperty active;
    public final SemanticProperty usrLastLogin;
    public final SemanticProperty creator;
    public final SemanticProperty usrPassword;
    public final SemanticProperty usrLogin;
    public final SemanticProperty hasRole;
    public final SemanticProperty usrSecurityQuestion;
    public final SemanticProperty usrSecurityAnswer;
    public final SemanticProperty title;
    public final SemanticProperty xml;
    public final SemanticProperty description;
    public final SemanticProperty hasPSTPortlets;
    public final SemanticProperty PSTType;
    public final SemanticProperty deleted;
    public final SemanticProperty template;
    public final SemanticProperty priority;
    public final SemanticProperty hasPFlowRef;
    public final SemanticProperty index;
    public final SemanticProperty hasRoleRef;
    public final SemanticProperty hasRule;
    public final SemanticProperty actualVersion;
    public final SemanticProperty lastVersion;
    public final SemanticProperty ipFilterAction;
    public final SemanticProperty ipFilterNumber;
    public final SemanticProperty hasRuleRef;
    public final SemanticProperty value;
    public final SemanticProperty hasCalendar;
    public final SemanticProperty frmTextAreaRows;
    public final SemanticProperty hasPortletRef;
    public final SemanticProperty hasObjectAction;
    public final SemanticProperty hasBehavior;
    public final SemanticProperty hasTemplateRef;
    public final SemanticProperty pflow;
    public final SemanticProperty rule;
    public final SemanticProperty hidden;
    public final SemanticProperty language;
    public final SemanticProperty webPage;
    public final SemanticProperty dnsDefault;
    public final SemanticProperty hasGroupedTemplate;
    public final SemanticProperty hasPortlet;
    public final SemanticProperty templateGroup;
    public final SemanticProperty propRequired;
    public final SemanticProperty propSelectValues;
    public final SemanticProperty propHidden;
    public final SemanticProperty propGroup;
    public final SemanticProperty propPromptMessage;
    public final SemanticProperty propInvalidMessage;
    public final SemanticProperty formElement;
    public final SemanticProperty propEditable;
    public final SemanticProperty hasPermission;
    public final SemanticProperty versionLockedBy;
    public final SemanticProperty previousVersion;
    public final SemanticProperty versionFile;
    public final SemanticProperty versionComment;
    public final SemanticProperty nextVersion;
    public final SemanticProperty versionNumber;
    public final SemanticProperty actGroup;
    public final SemanticProperty hasCreateProperty;
    public final SemanticProperty hasViewProperty;
    public final SemanticProperty hasEditProperty;
    public final SemanticProperty camp;
    public final SemanticProperty hits;
    public final SemanticProperty indexable;
    public final SemanticProperty portletWindow;
    public final SemanticProperty xmlConf;
    public final SemanticProperty views;
    public final SemanticProperty portletSubType;
    public final SemanticProperty portletType;
    public final SemanticProperty role;
    public final SemanticProperty formMode;
    public final SemanticProperty formView;
    public final SemanticProperty webPageSortName;
    public final SemanticProperty webPageURLType;
    public final SemanticProperty webPageDiskUsage;
    public final SemanticProperty hasWebPageVirtualParent;
    public final SemanticProperty hasWebPageVirtualChild;
    public final SemanticProperty hasWebPageChild;
    public final SemanticProperty webPageURL;
    public final SemanticProperty webPageParent;
    public final SemanticProperty homePage;
    public final SemanticProperty userRepository;
    public final SemanticProperty portlet;
    public final SemanticProperty portletBundle;
    public final SemanticProperty portletCache;
    public final SemanticProperty portletClassName;
    public final SemanticProperty hasPTPortlet;
    public final SemanticProperty portletMode;
    public final SemanticProperty hasPTSubType;


    public SWBVocabulary()
    {

         SemanticVocabulary vocabulary=SWBPlatform.getSemanticMgr().getVocabulary();
        // Classes
        swb_User=vocabulary.getSemanticClass(URI+"User");
        swb_Calendar=vocabulary.getSemanticClass(URI+"Calendar");
        swb_Community=vocabulary.getSemanticClass(URI+"Community");
        swb_PortletSubType=vocabulary.getSemanticClass(URI+"PortletSubType");
        swb_TemplateRef=vocabulary.getSemanticClass(URI+"TemplateRef");
        swb_Templateable=vocabulary.getSemanticClass(URI+"Templateable");
        swb_Deleteable=vocabulary.getSemanticClass(URI+"Deleteable");
        swb_Reference=vocabulary.getSemanticClass(URI+"Reference");
        swb_Roleable=vocabulary.getSemanticClass(URI+"Roleable");
        swb_PFlowRefable=vocabulary.getSemanticClass(URI+"PFlowRefable");
        swb_Sortable=vocabulary.getSemanticClass(URI+"Sortable");
        swb_Traceable=vocabulary.getSemanticClass(URI+"Traceable");
        swb_RoleRefable=vocabulary.getSemanticClass(URI+"RoleRefable");
        swb_Ruleable=vocabulary.getSemanticClass(URI+"Ruleable");
        swb_PFlow=vocabulary.getSemanticClass(URI+"PFlow");
        swb_IPFilter=vocabulary.getSemanticClass(URI+"IPFilter");
        swb_RuleRefable=vocabulary.getSemanticClass(URI+"RuleRefable");
        swb_Valueable=vocabulary.getSemanticClass(URI+"Valueable");
        swb_Calendarable=vocabulary.getSemanticClass(URI+"Calendarable");
        swb_TextArea=vocabulary.getSemanticClass(URI+"TextArea");
        swb_PortletRefable=vocabulary.getSemanticClass(URI+"PortletRefable");
        swb_DisplayObject=vocabulary.getSemanticClass(URI+"DisplayObject");
        swb_Permission=vocabulary.getSemanticClass(URI+"Permission");
        swb_TemplateRefable=vocabulary.getSemanticClass(URI+"TemplateRefable");
        swb_PFlowRef=vocabulary.getSemanticClass(URI+"PFlowRef");
        swb_RuleRef=vocabulary.getSemanticClass(URI+"RuleRef");
        swb_Referensable=vocabulary.getSemanticClass(URI+"Referensable");
        swb_Device=vocabulary.getSemanticClass(URI+"Device");
        swb_Hiddenable=vocabulary.getSemanticClass(URI+"Hiddenable");
        swb_Groupable=vocabulary.getSemanticClass(URI+"Groupable");
        swb_Localeable=vocabulary.getSemanticClass(URI+"Localeable");
        swb_Camp=vocabulary.getSemanticClass(URI+"Camp");
        swb_Dns=vocabulary.getSemanticClass(URI+"Dns");
        swb_TemplateGroup=vocabulary.getSemanticClass(URI+"TemplateGroup");
        swb_UserRepository=vocabulary.getSemanticClass(URI+"UserRepository");
        swb_Portletable=vocabulary.getSemanticClass(URI+"Portletable");
        swb_Template=vocabulary.getSemanticClass(URI+"Template");
        swb_DisplayProperty=vocabulary.getSemanticClass(URI+"DisplayProperty");
        swb_Role=vocabulary.getSemanticClass(URI+"Role");
        swb_Priorityable=vocabulary.getSemanticClass(URI+"Priorityable");
        swb_Activeable=vocabulary.getSemanticClass(URI+"Activeable");
        swb_VersionInfo=vocabulary.getSemanticClass(URI+"VersionInfo");
        swb_ObjectAction=vocabulary.getSemanticClass(URI+"ObjectAction");
        swb_FormView=vocabulary.getSemanticClass(URI+"FormView");
        swb_Portlet=vocabulary.getSemanticClass(URI+"Portlet");
        swb_Descriptiveable=vocabulary.getSemanticClass(URI+"Descriptiveable");
        swb_Versionable=vocabulary.getSemanticClass(URI+"Versionable");
        swb_RoleRef=vocabulary.getSemanticClass(URI+"RoleRef");
        swb_XMLable=vocabulary.getSemanticClass(URI+"XMLable");
        swb_Rule=vocabulary.getSemanticClass(URI+"Rule");
        swb_FormViewRef=vocabulary.getSemanticClass(URI+"FormViewRef");
        swb_XMLConfable=vocabulary.getSemanticClass(URI+"XMLConfable");
        swb_WebPage=vocabulary.getSemanticClass(URI+"WebPage");
        swb_WebPageable=vocabulary.getSemanticClass(URI+"WebPageable");
        swb_WebSite=vocabulary.getSemanticClass(URI+"WebSite");
        swb_ObjectGroup=vocabulary.getSemanticClass(URI+"ObjectGroup");
        swb_Language=vocabulary.getSemanticClass(URI+"Language");
        swb_PortletRef=vocabulary.getSemanticClass(URI+"PortletRef");
        swb_Indexable=vocabulary.getSemanticClass(URI+"Indexable");
        swb_PortletType=vocabulary.getSemanticClass(URI+"PortletType");
        swb_Text=vocabulary.getSemanticClass(URI+"Text");
        swb_Viewable=vocabulary.getSemanticClass(URI+"Viewable");



        //Properties
        created=vocabulary.getSemanticProperty(URI+"created");
        usrSecondLastName=vocabulary.getSemanticProperty(URI+"usrSecondLastName");
        modifiedBy=vocabulary.getSemanticProperty(URI+"modifiedBy");
        usrEmail=vocabulary.getSemanticProperty(URI+"usrEmail");
        updated=vocabulary.getSemanticProperty(URI+"updated");
        usrFirstName=vocabulary.getSemanticProperty(URI+"usrFirstName");
        usrLanguage=vocabulary.getSemanticProperty(URI+"usrLanguage");
        usrPasswordChanged=vocabulary.getSemanticProperty(URI+"usrPasswordChanged");
        usrLastName=vocabulary.getSemanticProperty(URI+"usrLastName");
        hasGroup=vocabulary.getSemanticProperty(URI+"hasGroup");
        active=vocabulary.getSemanticProperty(URI+"active");
        usrLastLogin=vocabulary.getSemanticProperty(URI+"usrLastLogin");
        creator=vocabulary.getSemanticProperty(URI+"creator");
        usrPassword=vocabulary.getSemanticProperty(URI+"usrPassword");
        usrLogin=vocabulary.getSemanticProperty(URI+"usrLogin");
        hasRole=vocabulary.getSemanticProperty(URI+"hasRole");
        usrSecurityQuestion=vocabulary.getSemanticProperty(URI+"usrSecurityQuestion");
        usrSecurityAnswer=vocabulary.getSemanticProperty(URI+"usrSecurityAnswer");
        title=vocabulary.getSemanticProperty(URI+"title");
        xml=vocabulary.getSemanticProperty(URI+"xml");
        description=vocabulary.getSemanticProperty(URI+"description");
        hasPSTPortlets=vocabulary.getSemanticProperty(URI+"hasPSTPortlets");
        PSTType=vocabulary.getSemanticProperty(URI+"PSTType");
        deleted=vocabulary.getSemanticProperty(URI+"deleted");
        template=vocabulary.getSemanticProperty(URI+"template");
        priority=vocabulary.getSemanticProperty(URI+"priority");
        hasPFlowRef=vocabulary.getSemanticProperty(URI+"hasPFlowRef");
        index=vocabulary.getSemanticProperty(URI+"index");
        hasRoleRef=vocabulary.getSemanticProperty(URI+"hasRoleRef");
        hasRule=vocabulary.getSemanticProperty(URI+"hasRule");
        actualVersion=vocabulary.getSemanticProperty(URI+"actualVersion");
        lastVersion=vocabulary.getSemanticProperty(URI+"lastVersion");
        ipFilterAction=vocabulary.getSemanticProperty(URI+"ipFilterAction");
        ipFilterNumber=vocabulary.getSemanticProperty(URI+"ipFilterNumber");
        hasRuleRef=vocabulary.getSemanticProperty(URI+"hasRuleRef");
        value=vocabulary.getSemanticProperty(URI+"value");
        hasCalendar=vocabulary.getSemanticProperty(URI+"hasCalendar");
        frmTextAreaRows=vocabulary.getSemanticProperty(URI+"frmTextAreaRows");
        hasPortletRef=vocabulary.getSemanticProperty(URI+"hasPortletRef");
        hasObjectAction=vocabulary.getSemanticProperty(URI+"hasObjectAction");
        hasBehavior=vocabulary.getSemanticProperty(URI+"hasBehavior");
        hasTemplateRef=vocabulary.getSemanticProperty(URI+"hasTemplateRef");
        pflow=vocabulary.getSemanticProperty(URI+"pflow");
        rule=vocabulary.getSemanticProperty(URI+"rule");
        hidden=vocabulary.getSemanticProperty(URI+"hidden");
        language=vocabulary.getSemanticProperty(URI+"language");
        webPage=vocabulary.getSemanticProperty(URI+"webPage");
        dnsDefault=vocabulary.getSemanticProperty(URI+"dnsDefault");
        hasGroupedTemplate=vocabulary.getSemanticProperty(URI+"hasGroupedTemplate");
        hasPortlet=vocabulary.getSemanticProperty(URI+"hasPortlet");
        templateGroup=vocabulary.getSemanticProperty(URI+"templateGroup");
        propRequired=vocabulary.getSemanticProperty(URI+"propRequired");
        propSelectValues=vocabulary.getSemanticProperty(URI+"propSelectValues");
        propHidden=vocabulary.getSemanticProperty(URI+"propHidden");
        propGroup=vocabulary.getSemanticProperty(URI+"propGroup");
        propPromptMessage=vocabulary.getSemanticProperty(URI+"propPromptMessage");
        propInvalidMessage=vocabulary.getSemanticProperty(URI+"propInvalidMessage");
        formElement=vocabulary.getSemanticProperty(URI+"formElement");
        propEditable=vocabulary.getSemanticProperty(URI+"propEditable");
        hasPermission=vocabulary.getSemanticProperty(URI+"hasPermission");
        versionLockedBy=vocabulary.getSemanticProperty(URI+"versionLockedBy");
        previousVersion=vocabulary.getSemanticProperty(URI+"previousVersion");
        versionFile=vocabulary.getSemanticProperty(URI+"versionFile");
        versionComment=vocabulary.getSemanticProperty(URI+"versionComment");
        nextVersion=vocabulary.getSemanticProperty(URI+"nextVersion");
        versionNumber=vocabulary.getSemanticProperty(URI+"versionNumber");
        actGroup=vocabulary.getSemanticProperty(URI+"actGroup");
        hasCreateProperty=vocabulary.getSemanticProperty(URI+"hasCreateProperty");
        hasViewProperty=vocabulary.getSemanticProperty(URI+"hasViewProperty");
        hasEditProperty=vocabulary.getSemanticProperty(URI+"hasEditProperty");
        camp=vocabulary.getSemanticProperty(URI+"camp");
        hits=vocabulary.getSemanticProperty(URI+"hits");
        indexable=vocabulary.getSemanticProperty(URI+"indexable");
        portletWindow=vocabulary.getSemanticProperty(URI+"portletWindow");
        xmlConf=vocabulary.getSemanticProperty(URI+"xmlConf");
        views=vocabulary.getSemanticProperty(URI+"views");
        portletSubType=vocabulary.getSemanticProperty(URI+"portletSubType");
        portletType=vocabulary.getSemanticProperty(URI+"portletType");
        role=vocabulary.getSemanticProperty(URI+"role");
        formMode=vocabulary.getSemanticProperty(URI+"formMode");
        formView=vocabulary.getSemanticProperty(URI+"formView");
        webPageSortName=vocabulary.getSemanticProperty(URI+"webPageSortName");
        webPageURLType=vocabulary.getSemanticProperty(URI+"webPageURLType");
        webPageDiskUsage=vocabulary.getSemanticProperty(URI+"webPageDiskUsage");
        hasWebPageVirtualParent=vocabulary.getSemanticProperty(URI+"hasWebPageVirtualParent");
        hasWebPageVirtualChild=vocabulary.getSemanticProperty(URI+"hasWebPageVirtualChild");
        hasWebPageChild=vocabulary.getSemanticProperty(URI+"hasWebPageChild");
        webPageURL=vocabulary.getSemanticProperty(URI+"webPageURL");
        webPageParent=vocabulary.getSemanticProperty(URI+"webPageParent");
        homePage=vocabulary.getSemanticProperty(URI+"homePage");
        userRepository=vocabulary.getSemanticProperty(URI+"userRepository");
        portlet=vocabulary.getSemanticProperty(URI+"portlet");
        portletBundle=vocabulary.getSemanticProperty(URI+"portletBundle");
        portletCache=vocabulary.getSemanticProperty(URI+"portletCache");
        portletClassName=vocabulary.getSemanticProperty(URI+"portletClassName");
        hasPTPortlet=vocabulary.getSemanticProperty(URI+"hasPTPortlet");
        portletMode=vocabulary.getSemanticProperty(URI+"portletMode");
        hasPTSubType=vocabulary.getSemanticProperty(URI+"hasPTSubType");
    }
}
