/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LanguageEditor.java
 *
 * Created on 26/08/2009, 10:45:58 AM
 */

package org.semanticwb.openoffice.ui.wizard;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.netbeans.spi.wizard.WizardPage;
import org.semanticwb.office.interfaces.LanguageInfo;

/**
 *
 * @author victor.lorenzana
 */
public class LanguageEditor extends WizardPage {

    LanguageInfo[] languages;
    /** Creates new form LanguageEditor */
    public LanguageEditor() {
        initComponents();
    }

    public void setLenguages(LanguageInfo[] languages)
    {
        this.languages=languages;
        DefaultTableModel model=(DefaultTableModel)this.jTableLenguages.getModel();
        int rows=model.getRowCount();
        for(int i=0;i<rows;i++)
        {
            model.removeRow(0);
        }
        for(LanguageInfo language :  languages)
        {
            Object[] data=new Object[]{language,""};
            model.addRow(data);
        }
    }
    public LanguageInfo[] getLanguages()
    {
        return languages;
    }
    public String[] getTitles()
    {
        ArrayList<String> values=new ArrayList<String>();
        DefaultTableModel model=(DefaultTableModel)this.jTableLenguages.getModel();
        int rows=model.getRowCount();
        for(int i=0;i<rows;i++)
        {
            Object value=model.getValueAt(i,1);
            values.add(value.toString());
        }
        return values.toArray(new String[values.size()]);
    }
    public void setLenguages(LanguageInfo[] lenguages,String[] titles)
    {
        DefaultTableModel model=(DefaultTableModel)this.jTableLenguages.getModel();
        this.setLenguages(lenguages);
        int irow=0;
        for(String title : titles)
        {
            model.setValueAt(title, irow, 1);
            irow++;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLenguages = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTableLenguages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lenguaje", "Titulo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLenguages);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLenguages;
    // End of variables declaration//GEN-END:variables

}
