/*
 * SelectCategory.java
 *
 * Created on 3 de junio de 2008, 11:03 AM
 */
package org.semanticwb.openoffice.ui.wizard;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeCellRenderer;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import org.netbeans.spi.wizard.Wizard;
import org.netbeans.spi.wizard.WizardPage;
import org.netbeans.spi.wizard.WizardPanelNavResult;
import org.semanticwb.office.interfaces.CategoryInfo;
import org.semanticwb.openoffice.OfficeApplication;
import org.semanticwb.openoffice.ui.dialogs.DialogAddCategory;

/**
 *
 * @author  victor.lorenzana
 */
public class SelectCategory extends WizardPage
{

    private static final String CATEGORY_ID = "categoryID";
    private static final String REPOSITORY_ID = "repositoryID";

    /** Creates new form SelectCategory */
    public SelectCategory()
    {
        initComponents();
        loadTree();
        this.getWizardDataMap().put(CATEGORY_ID, null);
        this.getWizardDataMap().put("repositoryName", null);
    }

    private void loadTree()
    {
        this.jTreeCategory.setCellRenderer(new TreeRender());
        this.jTreeCategory.setEditable(false);
        DefaultMutableTreeNode repositories = new RepositoryNode("Repositorios");
        DefaultTreeModel model = new DefaultTreeModel(repositories);
        this.jTreeCategory.setModel(model);

        try
        {
            for (String repository : OfficeApplication.getOfficeApplicationProxy().getRepositories())
            {
                DefaultMutableTreeNode repositoryNode = new RepositoryNode(repository);
                model.insertNodeInto(repositoryNode, repositories, 0);
                for (CategoryInfo category : OfficeApplication.getOfficeApplicationProxy().getCategories(repository))
                {
                    DefaultMutableTreeNode categoryNode = new CategoryNode(category.UDDI, category.title, category.description);
                    model.insertNodeInto(categoryNode, repositoryNode, 0);
                }
            }
        }
        catch (Exception wbe)
        {
            String message = wbe.getLocalizedMessage();
            if (wbe.getCause() != null)
            {
                Throwable cause = wbe.getCause();
                message += "\r\n" + cause.getMessage();
            }
            JOptionPane.showMessageDialog(this, message, getDescription(), JOptionPane.OK_OPTION);
            this.setProblem(message);
            return;
        }
        if (this.jTreeCategory.getRowCount() > 0)
        {
            this.jTreeCategory.expandRow(0);
        }

    }

    public static String getDescription()
    {
        return "Ubicación del contenido";
    }

    @Override
    public WizardPanelNavResult allowNext(String arg, Map map, Wizard wizard)
    {
        WizardPanelNavResult result = WizardPanelNavResult.PROCEED;
        if (this.getWizardDataMap().get(CATEGORY_ID) == null)
        {
            javax.swing.JOptionPane.showMessageDialog(null, "¡Debe seleccionar una categoria!", getDescription(), JOptionPane.ERROR_MESSAGE);
            this.jTreeCategory.requestFocus();
            result = WizardPanelNavResult.REMAIN_ON_PAGE;
        }
        return result;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonAddCategory = new javax.swing.JButton();
        jButtonDeletCategory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeCategory = new javax.swing.JTree();

        setPreferredSize(new java.awt.Dimension(500, 322));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jToolBar1.setRollover(true);

        jButtonAddCategory.setText("Agregar Categoria");
        jButtonAddCategory.setEnabled(false);
        jButtonAddCategory.setFocusable(false);
        jButtonAddCategory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddCategory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCategoryActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAddCategory);

        jButtonDeletCategory.setText("Borrar Categoria");
        jButtonDeletCategory.setEnabled(false);
        jButtonDeletCategory.setFocusable(false);
        jButtonDeletCategory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDeletCategory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDeletCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletCategoryActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonDeletCategory);

        jPanel1.add(jToolBar1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jTreeCategory.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeCategoryValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTreeCategory);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jButtonAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCategoryActionPerformed
    this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    Object selected = this.jTreeCategory.getLastSelectedPathComponent();
    if (selected != null && selected instanceof RepositoryNode)
    {
        RepositoryNode repositoryNode = (RepositoryNode) selected;
        DialogAddCategory addCategory = new DialogAddCategory(new JFrame(), true, repositoryNode.getName());
        addCategory.setVisible(true);
        if (!addCategory.isCancel())
        {
            try
            {
                for (CategoryInfo category : OfficeApplication.getOfficeApplicationProxy().getCategories(repositoryNode.getName()))
                {
                    DefaultMutableTreeNode categoryNode = new CategoryNode(category.UDDI, category.title, category.description);
                    ((DefaultTreeModel) jTreeCategory.getModel()).insertNodeInto(categoryNode, repositoryNode, 0);
                }
            }
            catch (Exception e)
            {
            }
        }
    }
    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_jButtonAddCategoryActionPerformed

private void jTreeCategoryValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeCategoryValueChanged
    this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    Object selected = this.jTreeCategory.getLastSelectedPathComponent();
    this.getWizardDataMap().put(CATEGORY_ID, null);
    this.getWizardDataMap().put(REPOSITORY_ID, null);
    if (selected != null && selected instanceof RepositoryNode)
    {
        if (((RepositoryNode) selected).getName().equals("Repositorios"))
        {
            this.jButtonAddCategory.setEnabled(false);
        }
        else
        {
            this.jButtonAddCategory.setEnabled(true);
        }
    }
    else
    {
        this.jButtonAddCategory.setEnabled(false);
    }
    this.jButtonDeletCategory.setEnabled(false);
    if (selected != null && selected instanceof CategoryNode)
    {
        String categoryId = ((CategoryNode) selected).getID();
        String repository = ((RepositoryNode) ((CategoryNode) selected).getParent()).getName();
        this.getWizardDataMap().put(CATEGORY_ID, categoryId);
        this.getWizardDataMap().put(REPOSITORY_ID, repository);
        try
        {
            if (OfficeApplication.getOfficeApplicationProxy().canDeleteCategory(repository, categoryId))
            {
                this.jButtonDeletCategory.setEnabled(true);
            }
        }
        catch (Exception e)
        {
        }
    }
    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_jTreeCategoryValueChanged

private void jButtonDeletCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletCategoryActionPerformed
    this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    String categoryId = (String) this.getWizardDataMap().get(CATEGORY_ID);
    String repository = (String) this.getWizardDataMap().get(REPOSITORY_ID);
    try
    {
        if (OfficeApplication.getOfficeApplicationProxy().deleteCategory(repository, categoryId))
        {
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTreeCategory.getLastSelectedPathComponent();
            if (node == null)
            {
                return;
            }
            DefaultMutableTreeNode parentNode = (DefaultMutableTreeNode) (node.getParent());
            if (parentNode == null)
            {
                return;//-- remove node --
            }
            parentNode.remove(node);
            ((DefaultTreeModel)jTreeCategory.getModel()).reload(parentNode);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No se puede borrar la categoria por que tiene contenidos", "Borrar categoria", JOptionPane.ERROR | JOptionPane.YES_NO_OPTION);
        }
    }
    catch (Exception e)
    {
    }
    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_jButtonDeletCategoryActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCategory;
    private javax.swing.JButton jButtonDeletCategory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTreeCategory;
    // End of variables declaration//GEN-END:variables
}

interface ToolTipTreeNode
{

    public String getToolTipText();
}

class RepositoryNode extends DefaultMutableTreeNode implements ToolTipTreeNode
{

    private JLabel component = new JLabel();
    private String name;

    public RepositoryNode(String name)
    {
        this.name = name;
        component.setText(name);
        component.setOpaque(true);
    }

    public String getToolTipText()
    {
        return this.name;
    }

    public String getName()
    {
        return name;
    }

    @Override
    public String toString()
    {
        this.hashCode();
        return name;
    }

    @Override
    public int hashCode()
    {
        return this.name.hashCode();
    }

    @Override
    public boolean equals(Object obj)
    {
        boolean equals = false;
        if (obj instanceof RepositoryNode)
        {
            equals = ((RepositoryNode) obj).name.equals(this.name);
        }
        return equals;
    }

    public JLabel getComponent()
    {
        return component;
    }
}

class CategoryNode extends DefaultMutableTreeNode implements ToolTipTreeNode
{

    private JLabel component = new JLabel();
    private String id;
    private String title;
    private String description;

    public CategoryNode(String id, String title, String description)
    {
        this.id = id;
        this.title = title;
        this.description = description;

        component.setText(title);
        component.setToolTipText(description);
        component.setOpaque(true);
    }

    public String getToolTipText()
    {
        return description;
    }

    @Override
    public String toString()
    {
        this.hashCode();
        return title;
    }

    @Override
    public int hashCode()
    {
        return this.title.hashCode();
    }

    @Override
    public boolean equals(Object obj)
    {
        boolean equals = false;
        if (obj instanceof CategoryNode)
        {
            equals = ((CategoryNode) obj).title.equals(this.title);
        }
        return equals;
    }

    public String getID()
    {
        return id;
    }

    public String getDescription()
    {
        return this.description;
    }

    public JLabel getComponent()
    {
        return component;
    }
}

class TreeRender extends JPanel implements TreeCellRenderer
{

    public Component getTreeCellRendererComponent(JTree tree, Object object, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus)
    {
        Component component = this;
        tree.setToolTipText("");
        if (object instanceof CategoryNode)
        {
            component = ((CategoryNode) object).getComponent();
            if (hasFocus)
            {
                tree.setToolTipText(((CategoryNode) object).getDescription());
            }
        }
        if (object instanceof RepositoryNode)
        {
            component = ((RepositoryNode) object).getComponent();
        //component.setFont(tree.getFont());
        }
        if (component != null)
        {
            JLabel label = (JLabel) component;

            label.setFont(tree.getFont());
            if (expanded)
            {
                label.setIcon(new javax.swing.ImageIcon(getClass().getResource("open.gif")));
            }
            else
            {
                label.setIcon(new javax.swing.ImageIcon(getClass().getResource("close.gif")));
            }
            if (selected)
            {
                label.setBackground(Color.BLUE);
                label.setForeground(Color.WHITE);
            }
            else
            {
                label.setBackground(tree.getBackground());
                label.setForeground(tree.getForeground());
            }
        }
        return component;

    }
}
