/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogRegularPeriods.java
 *
 * Created on 12/02/2009, 03:45:09 PM
 */

package org.semanticwb.openoffice.ui.dialogs;

import org.w3c.dom.Document;

/**
 *
 * @author victor.lorenzana
 */
public class DialogRegularPeriods extends java.awt.Dialog {

    private Document document;
    /** Creates new form DialogRegularPeriods */
    public DialogRegularPeriods(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Document getDocument()
    {
        if(document==null)
        {
            org.jdom.output.DOMOutputter out=new org.jdom.output.DOMOutputter();
            try
            {
                document=out.output(new org.jdom.Document());
            }
            catch(Exception e)
            {

            }
        }
        return document;
    }
    public void setDocument(Document document)
    {
        this.document=document;
        init();
    }
    private void init()
    {
        if(document!=null)
        {
            if(document.getElementsByTagName("weekly").getLength()>0)
            {
                jRadioButtonWeek.setSelected(true);
            }
            if(document.getElementsByTagName("monthly").getLength()>0)
            {
                jRadioButtonWeek.setSelected(true);
            }
            if(document.getElementsByTagName("yearly").getLength()>0)
            {
                jRadioButtonYear.setSelected(true);
            }
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPeriodicidad = new javax.swing.ButtonGroup();
        buttonGroupMensual = new javax.swing.ButtonGroup();
        buttonGroupAnual = new javax.swing.ButtonGroup();
        jPanelBody = new javax.swing.JPanel();
        jPanelCommands = new javax.swing.JPanel();
        jButtonok = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanelConfigurations = new javax.swing.JPanel();
        jPanelWeek = new javax.swing.JPanel();
        jRadioButtonWeek = new javax.swing.JRadioButton();
        jCheckBoxWeekMonday = new javax.swing.JCheckBox();
        jCheckBoxWeekTuesday = new javax.swing.JCheckBox();
        jCheckBoxWeekWednesday = new javax.swing.JCheckBox();
        jCheckBoxWeekThursday = new javax.swing.JCheckBox();
        jCheckBoxWeekFriday = new javax.swing.JCheckBox();
        jCheckBoxWeekSaturday = new javax.swing.JCheckBox();
        jCheckBoxWeekSunday = new javax.swing.JCheckBox();
        jPanelOthers = new javax.swing.JPanel();
        jPanelMonth = new javax.swing.JPanel();
        jRadioButtonMonth = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMonthDay = new javax.swing.JComboBox();
        jCheckBoxMonthMonday = new javax.swing.JCheckBox();
        jCheckBoxMonthTuesday = new javax.swing.JCheckBox();
        jCheckBoxMonthWednesday = new javax.swing.JCheckBox();
        jCheckBoxMonthThursday = new javax.swing.JCheckBox();
        jCheckBoxMonthFriday = new javax.swing.JCheckBox();
        jCheckBoxMonthSaturday = new javax.swing.JCheckBox();
        jCheckBoxMonthSunday = new javax.swing.JCheckBox();
        jRadioButtonMonthOption1 = new javax.swing.JRadioButton();
        jRadioButtonMonthOption2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerMonthDay = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jPanelYear = new javax.swing.JPanel();
        jRadioButtonYear = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxYearDay = new javax.swing.JComboBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jSpinnerYearDay = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jPanelUseRegularPeriods = new javax.swing.JPanel();
        jCheckBoxUseRegularPeriods = new javax.swing.JCheckBox();

        setLocationRelativeTo(null);
        setModal(true);
        setResizable(false);
        setTitle("Calendarización con Periodos Regulares");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanelBody.setLayout(new java.awt.BorderLayout());

        jPanelCommands.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanelCommands.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonok.setText("Aceptar");
        jButtonok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonokActionPerformed(evt);
            }
        });
        jPanelCommands.add(jButtonok);

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelCommands.add(jButtonCancel);

        jPanelBody.add(jPanelCommands, java.awt.BorderLayout.SOUTH);

        jPanelConfigurations.setLayout(new java.awt.BorderLayout());

        jPanelWeek.setBorder(javax.swing.BorderFactory.createTitledBorder("Periodicidad Semanal"));
        jPanelWeek.setPreferredSize(new java.awt.Dimension(100, 90));

        buttonGroupPeriodicidad.add(jRadioButtonWeek);
        jRadioButtonWeek.setSelected(true);
        jRadioButtonWeek.setText("Semanal");

        jCheckBoxWeekMonday.setText("Lunes");

        jCheckBoxWeekTuesday.setText("Martes");

        jCheckBoxWeekWednesday.setText("Miércoles");

        jCheckBoxWeekThursday.setText("Jueves");

        jCheckBoxWeekFriday.setText("Viernes");

        jCheckBoxWeekSaturday.setText("Sabado");

        jCheckBoxWeekSunday.setText("Domingo");

        javax.swing.GroupLayout jPanelWeekLayout = new javax.swing.GroupLayout(jPanelWeek);
        jPanelWeek.setLayout(jPanelWeekLayout);
        jPanelWeekLayout.setHorizontalGroup(
            jPanelWeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWeekLayout.createSequentialGroup()
                .addComponent(jRadioButtonWeek)
                .addGap(52, 52, 52)
                .addGroup(jPanelWeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxWeekMonday)
                    .addComponent(jCheckBoxWeekSaturday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelWeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWeekLayout.createSequentialGroup()
                        .addComponent(jCheckBoxWeekTuesday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxWeekWednesday)
                        .addGap(2, 2, 2)
                        .addComponent(jCheckBoxWeekThursday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxWeekFriday))
                    .addComponent(jCheckBoxWeekSunday))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelWeekLayout.setVerticalGroup(
            jPanelWeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWeekLayout.createSequentialGroup()
                .addGroup(jPanelWeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWeekLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonWeek))
                    .addGroup(jPanelWeekLayout.createSequentialGroup()
                        .addGroup(jPanelWeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxWeekMonday)
                            .addComponent(jCheckBoxWeekTuesday)
                            .addComponent(jCheckBoxWeekWednesday)
                            .addComponent(jCheckBoxWeekThursday)
                            .addComponent(jCheckBoxWeekFriday))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelWeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxWeekSaturday)
                            .addComponent(jCheckBoxWeekSunday))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanelConfigurations.add(jPanelWeek, java.awt.BorderLayout.NORTH);

        jPanelOthers.setLayout(new java.awt.BorderLayout());

        jPanelMonth.setBorder(javax.swing.BorderFactory.createTitledBorder("Periodicidad Mensual"));
        jPanelMonth.setPreferredSize(new java.awt.Dimension(100, 130));

        buttonGroupPeriodicidad.add(jRadioButtonMonth);
        jRadioButtonMonth.setText("Mensual");

        jLabel1.setText("El:");

        jComboBoxMonthDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primer", "Segundo", "Tercer", "Cuarto", "Último" }));

        jCheckBoxMonthMonday.setText("Lu");

        jCheckBoxMonthTuesday.setText("Ma");

        jCheckBoxMonthWednesday.setText("Mi");

        jCheckBoxMonthThursday.setText("Ju");

        jCheckBoxMonthFriday.setText("Vi");

        jCheckBoxMonthSaturday.setText("Sa");

        jCheckBoxMonthSunday.setText("Do");

        buttonGroupMensual.add(jRadioButtonMonthOption1);
        jRadioButtonMonthOption1.setSelected(true);

        buttonGroupMensual.add(jRadioButtonMonthOption2);

        jLabel2.setText("El:");

        jSpinnerMonthDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel3.setText("de cada:");

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, Integer.valueOf(12), Integer.valueOf(1)));

        jLabel4.setText("Meses");

        jLabel5.setText("de cada:");

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, Integer.valueOf(12), Integer.valueOf(1)));

        jLabel6.setText("Meses");

        javax.swing.GroupLayout jPanelMonthLayout = new javax.swing.GroupLayout(jPanelMonth);
        jPanelMonth.setLayout(jPanelMonthLayout);
        jPanelMonthLayout.setHorizontalGroup(
            jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMonthLayout.createSequentialGroup()
                .addComponent(jRadioButtonMonth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMonthLayout.createSequentialGroup()
                        .addComponent(jRadioButtonMonthOption2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(jSpinnerMonthDay)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMonthLayout.createSequentialGroup()
                        .addComponent(jRadioButtonMonthOption1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxMonthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxMonthFriday)
                            .addComponent(jCheckBoxMonthMonday))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxMonthSaturday)
                            .addComponent(jCheckBoxMonthTuesday))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMonthLayout.createSequentialGroup()
                                .addComponent(jCheckBoxMonthWednesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxMonthThursday)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addComponent(jCheckBoxMonthSunday))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanelMonthLayout.setVerticalGroup(
            jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMonthLayout.createSequentialGroup()
                        .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addComponent(jRadioButtonMonth))
                    .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxMonthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButtonMonthOption1)
                        .addComponent(jLabel1))
                    .addGroup(jPanelMonthLayout.createSequentialGroup()
                        .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxMonthMonday)
                            .addComponent(jCheckBoxMonthWednesday)
                            .addComponent(jCheckBoxMonthThursday)
                            .addComponent(jCheckBoxMonthTuesday))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxMonthFriday)
                            .addComponent(jCheckBoxMonthSunday)
                            .addComponent(jCheckBoxMonthSaturday))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerMonthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonMonthOption2)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanelOthers.add(jPanelMonth, java.awt.BorderLayout.NORTH);

        jPanelYear.setBorder(javax.swing.BorderFactory.createTitledBorder("Periodicidad Anual"));
        jPanelYear.setPreferredSize(new java.awt.Dimension(500, 160));

        buttonGroupPeriodicidad.add(jRadioButtonYear);
        jRadioButtonYear.setText("Anual");

        buttonGroupAnual.add(jRadioButton6);
        jRadioButton6.setSelected(true);

        jLabel7.setText("El:");

        jComboBoxYearDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primer", "Segundo", "Tercer", "Cuarto", "Último" }));

        jCheckBox15.setText("Lu");

        jCheckBox16.setText("Ma");

        jCheckBox17.setText("Vi");

        jCheckBox18.setText("Sa");

        jCheckBox19.setText("Do");

        jCheckBox20.setText("Mi");

        jCheckBox21.setText("Ju");

        jLabel8.setText("de:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        buttonGroupAnual.add(jRadioButton7);

        jLabel9.setText("El:");

        jSpinnerYearDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel10.setText("de:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel11.setText("de cada:");

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, Integer.valueOf(999), Integer.valueOf(1)));

        jLabel12.setText("años");

        javax.swing.GroupLayout jPanelYearLayout = new javax.swing.GroupLayout(jPanelYear);
        jPanelYear.setLayout(jPanelYearLayout);
        jPanelYearLayout.setHorizontalGroup(
            jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelYearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonYear)
                .addGap(8, 8, 8)
                .addGroup(jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelYearLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxYearDay, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox17)
                            .addComponent(jCheckBox15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox18)
                            .addComponent(jCheckBox16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelYearLayout.createSequentialGroup()
                                .addComponent(jCheckBox20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox19)))
                    .addGroup(jPanelYearLayout.createSequentialGroup()
                        .addComponent(jRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerYearDay, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner5, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanelYearLayout.setVerticalGroup(
            jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelYearLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox21)
                    .addGroup(jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(jPanelYearLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonYear)
                .addGap(75, 75, 75))
            .addGroup(jPanelYearLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jCheckBox15)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(jPanelYearLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jCheckBox16)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(jPanelYearLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jCheckBox20)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(jPanelYearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxYearDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton6))
                .addGap(3, 3, 3)
                .addGroup(jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox19)
                        .addComponent(jCheckBox18))
                    .addComponent(jCheckBox17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25)
                .addGroup(jPanelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jLabel9)
                    .addComponent(jSpinnerYearDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        jPanelOthers.add(jPanelYear, java.awt.BorderLayout.CENTER);

        jPanelConfigurations.add(jPanelOthers, java.awt.BorderLayout.CENTER);

        jPanelBody.add(jPanelConfigurations, java.awt.BorderLayout.CENTER);

        add(jPanelBody, java.awt.BorderLayout.CENTER);

        jPanelUseRegularPeriods.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanelUseRegularPeriods.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBoxUseRegularPeriods.setText("Usar Periodos Regulares");
        jPanelUseRegularPeriods.add(jCheckBoxUseRegularPeriods);

        add(jPanelUseRegularPeriods, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonokActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonokActionPerformed
    {//GEN-HEADEREND:event_jButtonokActionPerformed
        this.setVisible(false);        
    }//GEN-LAST:event_jButtonokActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogRegularPeriods dialog = new DialogRegularPeriods(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAnual;
    private javax.swing.ButtonGroup buttonGroupMensual;
    private javax.swing.ButtonGroup buttonGroupPeriodicidad;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonok;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBoxMonthFriday;
    private javax.swing.JCheckBox jCheckBoxMonthMonday;
    private javax.swing.JCheckBox jCheckBoxMonthSaturday;
    private javax.swing.JCheckBox jCheckBoxMonthSunday;
    private javax.swing.JCheckBox jCheckBoxMonthThursday;
    private javax.swing.JCheckBox jCheckBoxMonthTuesday;
    private javax.swing.JCheckBox jCheckBoxMonthWednesday;
    private javax.swing.JCheckBox jCheckBoxUseRegularPeriods;
    private javax.swing.JCheckBox jCheckBoxWeekFriday;
    private javax.swing.JCheckBox jCheckBoxWeekMonday;
    private javax.swing.JCheckBox jCheckBoxWeekSaturday;
    private javax.swing.JCheckBox jCheckBoxWeekSunday;
    private javax.swing.JCheckBox jCheckBoxWeekThursday;
    private javax.swing.JCheckBox jCheckBoxWeekTuesday;
    private javax.swing.JCheckBox jCheckBoxWeekWednesday;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBoxMonthDay;
    private javax.swing.JComboBox jComboBoxYearDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelCommands;
    private javax.swing.JPanel jPanelConfigurations;
    private javax.swing.JPanel jPanelMonth;
    private javax.swing.JPanel jPanelOthers;
    private javax.swing.JPanel jPanelUseRegularPeriods;
    private javax.swing.JPanel jPanelWeek;
    private javax.swing.JPanel jPanelYear;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButtonMonth;
    private javax.swing.JRadioButton jRadioButtonMonthOption1;
    private javax.swing.JRadioButton jRadioButtonMonthOption2;
    private javax.swing.JRadioButton jRadioButtonWeek;
    private javax.swing.JRadioButton jRadioButtonYear;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinnerMonthDay;
    private javax.swing.JSpinner jSpinnerYearDay;
    // End of variables declaration//GEN-END:variables

}
