/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogPreview.java
 *
 * Created on 4/03/2009, 05:15:00 PM
 */
package org.semanticwb.openoffice.ui.dialogs;

import chrriis.dj.nativeswing.NativeSwing;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import java.awt.Frame;
import java.io.IOException;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.semanticwb.openoffice.ui.icons.ImageLoader;

/**
 *
 * @author victor.lorenzana
 */
public class DialogPreview extends java.awt.Dialog
{

    static
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ue)
        {
            // No debe hacer nada
            System.out.println(ue.getMessage());
        }
    }
    private final URL url;

    public DialogPreview(URL url, String title)
    {
        this(url, true, title);
    }
    /** Creates new form DialogPreview */
    public DialogPreview(URL url, boolean showAddress, String title)
    {
        super(new JFrame(title), true);
        this.url = url;
        initComponents();
        if (title != null)
        {
            this.setTitle(title);
        }
        if(!showAddress)
        {
            JOptionPane.showMessageDialog(null, "Para ver contenido, se solicitará su clave y contraseña",this.getTitle(),JOptionPane.OK_OPTION | JOptionPane.INFORMATION_MESSAGE);
        }
        this.setIconImage(ImageLoader.images.get("semius").getImage());
        NativeSwing.initialize();
        NativeInterface.open();
        JWebBrowser webBrowser = new JWebBrowser();
        webBrowser.setBarsVisible(false);
        webBrowser.navigate(url.toString());
        this.jTextFieldURL.setVisible(showAddress);
        this.jTextFieldURL.setText(url.toString());
        this.jLabelWebAddress.setVisible(showAddress);
        this.jButtonOpenBrowser.setVisible(showAddress);
        this.jPanel2.add(webBrowser);
        this.setLocationRelativeTo(null);
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jTextFieldURL = new javax.swing.JTextField();
        jLabelWebAddress = new javax.swing.JLabel();
        jButtonOpenBrowser = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 50));

        jButtonClose.setText("Cerrar");
        jButtonClose.setToolTipText("No se puede navegar con esta vista");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jTextFieldURL.setEditable(false);

        jLabelWebAddress.setText("Dirección Web:");

        jButtonOpenBrowser.setText("Abrir en un navegador");
        jButtonOpenBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenBrowserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelWebAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldURL, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpenBrowser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonOpenBrowser)
                    .addComponent(jTextFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWebAddress))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel2.setLayout(new java.awt.BorderLayout());
        add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCloseActionPerformed
    {//GEN-HEADEREND:event_jButtonCloseActionPerformed

        this.setVisible(false);
}//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonOpenBrowserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOpenBrowserActionPerformed
    {//GEN-HEADEREND:event_jButtonOpenBrowserActionPerformed

        showInBrowser(this.url.toString(), new Frame());
}//GEN-LAST:event_jButtonOpenBrowserActionPerformed
    public static boolean showInBrowser(String url, Frame frame)
    {
        //minimizes the app
        if (frame != null)
        {
            frame.setExtendedState(JFrame.ICONIFIED);
        }

        String os = System.getProperty("os.name").toLowerCase();
        Runtime rt = Runtime.getRuntime();
        try
        {
            if (os.indexOf("win") >= 0)
            {
                String[] cmd = new String[4];
                cmd[0] = "cmd.exe";
                cmd[1] = "/C";
                cmd[2] = "start";
                cmd[3] = url;
                rt.exec(cmd);
            }
            else if (os.indexOf("mac") >= 0)
            {
                rt.exec("open " + url);
            }
            else
            {
                //prioritized 'guess' of users' preference
                String[] browsers =
                {
                    "epiphany", "firefox", "mozilla", "konqueror",
                    "netscape", "opera", "links", "lynx"
                };

                StringBuffer cmd = new StringBuffer();
                for (int i = 0; i < browsers.length; i++)
                {
                    cmd.append((i == 0 ? "" : " || ") + browsers[i] + " \"" + url + "\" ");
                }

                rt.exec(new String[]
                        {
                            "sh", "-c", cmd.toString()
                        });
            }
        }
        catch (IOException e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(frame,
                    "\n\n El sistema falló al tratar de invocar su navegador por defecto intentando acceder a: \n\n " + url + "\n\n",
                    "Error de navegador",
                    JOptionPane.WARNING_MESSAGE);

            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                try
                {
                    URL url = new URL("http://www.infotec.com.mx");
                    DialogPreview dialog = new DialogPreview(url, "Demo");
                    dialog.addWindowListener(new java.awt.event.WindowAdapter()
                    {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e)
                        {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                }
                catch (Exception e)
                {
                }

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonOpenBrowser;
    private javax.swing.JLabel jLabelWebAddress;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldURL;
    // End of variables declaration//GEN-END:variables
}
