/*
 * DialogAbout.java
 *
 * Created on 4 de junio de 2008, 04:04 PM
 */

package org.semanticwb.openoffice.ui.dialogs;

import java.awt.BorderLayout;

/**
 *
 * @author  victor.lorenzana
 */
public class DialogAbout extends javax.swing.JDialog {
    
    /** Creates new form DialogAbout */
    public DialogAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.add(new AboutBackGound(this),BorderLayout.CENTER);
        this.setSize(505, 335);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de Semantic INFOTEC WebBuilder 4");
        setResizable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
