/*
 * DialogContentInformation.java
 *
 * Created on 4 de junio de 2008, 10:09 AM
 */
package org.semanticwb.openoffice.ui.dialogs;

/**
 *
 * @author  victor.lorenzana
 */
public class DialogContentInformation extends javax.swing.JDialog
{

    /** Creates new form DialogContentInformation */
    public DialogContentInformation(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelButtons = new javax.swing.JPanel();
        jButtonAccept = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonSendToAuthorize = new javax.swing.JButton();
        jButtonSchuddler = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelInformation = new javax.swing.JPanel();
        jLabel1Id = new javax.swing.JLabel();
        jLabel1Title = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jLabel1Description = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jLabel1DateofModification = new javax.swing.JLabel();
        jLabel1DisplayDateOfModification = new javax.swing.JLabel();
        jLabel1State = new javax.swing.JLabel();
        jLabel1DisplayState = new javax.swing.JLabel();
        jLabel1Activity = new javax.swing.JLabel();
        jLabel2DisplayActivity = new javax.swing.JLabel();
        jLabelVisible = new javax.swing.JLabel();
        jRadioButtonVisibleYes = new javax.swing.JRadioButton();
        jRadioButtonVisibleNo = new javax.swing.JRadioButton();
        jPanelPermissions = new javax.swing.JPanel();
        jCheckBoxAllowEditFromWeb = new javax.swing.JCheckBox();
        jLabelRol = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox();
        jPanelRolsAndRules = new javax.swing.JPanel();
        jPanelRol = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListRol = new javax.swing.JList();
        jPanelRules = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListRules = new javax.swing.JList();
        jPanelTypeOfDisplay = new javax.swing.JPanel();
        jRadioButtonWeb = new javax.swing.JRadioButton();
        jRadioButtonOffice = new javax.swing.JRadioButton();
        jPanelChangePagContenido = new javax.swing.JPanel();
        pagContenido1 = new org.semanticwb.openoffice.ui.wizard.PagContenido();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información del Contenido");
        setModal(true);
        setResizable(false);

        jPanelButtons.setPreferredSize(new java.awt.Dimension(100, 50));

        jButtonAccept.setText("Aceptar");

        jButtonCancel.setText("Cancelar");

        jButtonSendToAuthorize.setText("Enviar a autorizar");

        jButtonSchuddler.setText("Calendarizar");

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSendToAuthorize)
                .addGap(18, 18, 18)
                .addComponent(jButtonSchuddler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButtonCancel)
                .addGap(18, 18, 18)
                .addComponent(jButtonAccept)
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAccept)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSendToAuthorize)
                    .addComponent(jButtonSchuddler))
                .addContainerGap())
        );

        getContentPane().add(jPanelButtons, java.awt.BorderLayout.SOUTH);

        jLabel1Id.setText("Identificador:");

        jLabel1Title.setText("Título:");

        jLabel13.setText("1542");

        jLabel1Description.setText("Descripción:");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescription);

        jLabel1DateofModification.setText("Fecha de Modificación:");

        jLabel1DisplayDateOfModification.setText("16 de Mayo de 2008 10:40 a.m.");

        jLabel1State.setText("Estado en el proceso de autorización:");

        jLabel1DisplayState.setText("Revisión");

        jLabel1Activity.setText("Actividad en el proceso de autorización:");

        jLabel2DisplayActivity.setText("Autorización por parte de Diseño gráfico");

        jLabelVisible.setText("Visible");

        buttonGroup1.add(jRadioButtonVisibleYes);
        jRadioButtonVisibleYes.setSelected(true);
        jRadioButtonVisibleYes.setText("Sí");

        buttonGroup1.add(jRadioButtonVisibleNo);
        jRadioButtonVisibleNo.setText("No");

        javax.swing.GroupLayout jPanelInformationLayout = new javax.swing.GroupLayout(jPanelInformation);
        jPanelInformation.setLayout(jPanelInformationLayout);
        jPanelInformationLayout.setHorizontalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1Description)
                    .addComponent(jLabel1Id)
                    .addComponent(jLabel1Title)
                    .addComponent(jLabel1DateofModification)
                    .addComponent(jLabel1State)
                    .addComponent(jLabel1Activity)
                    .addComponent(jLabelVisible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformationLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap())
                    .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInformationLayout.createSequentialGroup()
                            .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1DisplayDateOfModification)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                .addComponent(jLabel2DisplayActivity)
                                .addComponent(jLabel1DisplayState))
                            .addGap(21, 21, 21))
                        .addGroup(jPanelInformationLayout.createSequentialGroup()
                            .addComponent(jRadioButtonVisibleYes)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButtonVisibleNo)
                            .addContainerGap(179, Short.MAX_VALUE)))))
        );
        jPanelInformationLayout.setVerticalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Id)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Title)
                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1Description)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1DateofModification)
                    .addComponent(jLabel1DisplayDateOfModification))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1State)
                    .addComponent(jLabel1DisplayState))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Activity)
                    .addComponent(jLabel2DisplayActivity))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonVisibleYes)
                        .addComponent(jRadioButtonVisibleNo))
                    .addComponent(jLabelVisible))
                .addGap(44, 44, 44))
        );

        jTabbedPane2.addTab("Información del contenido", jPanelInformation);

        jCheckBoxAllowEditFromWeb.setText("Permitir editar desde el navegador");

        jLabelRol.setText("Rol permitido para su edición");

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanelRolsAndRules.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Roles y Reglas Permitidas para su visualización", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jPanelRol.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Roles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jListRol.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListRol);

        javax.swing.GroupLayout jPanelRolLayout = new javax.swing.GroupLayout(jPanelRol);
        jPanelRol.setLayout(jPanelRolLayout);
        jPanelRolLayout.setHorizontalGroup(
            jPanelRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelRolLayout.setVerticalGroup(
            jPanelRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRolLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelRules.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reglas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jListRules.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListRules);

        javax.swing.GroupLayout jPanelRulesLayout = new javax.swing.GroupLayout(jPanelRules);
        jPanelRules.setLayout(jPanelRulesLayout);
        jPanelRulesLayout.setHorizontalGroup(
            jPanelRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRulesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelRulesLayout.setVerticalGroup(
            jPanelRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRulesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelRolsAndRulesLayout = new javax.swing.GroupLayout(jPanelRolsAndRules);
        jPanelRolsAndRules.setLayout(jPanelRolsAndRulesLayout);
        jPanelRolsAndRulesLayout.setHorizontalGroup(
            jPanelRolsAndRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRolsAndRulesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRolsAndRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelRolsAndRulesLayout.setVerticalGroup(
            jPanelRolsAndRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRolsAndRulesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRules, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPermissionsLayout = new javax.swing.GroupLayout(jPanelPermissions);
        jPanelPermissions.setLayout(jPanelPermissionsLayout);
        jPanelPermissionsLayout.setHorizontalGroup(
            jPanelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPermissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxAllowEditFromWeb)
                    .addComponent(jPanelRolsAndRules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPermissionsLayout.createSequentialGroup()
                        .addComponent(jLabelRol)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxRol, 0, 301, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPermissionsLayout.setVerticalGroup(
            jPanelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPermissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxAllowEditFromWeb)
                .addGap(10, 10, 10)
                .addGroup(jPanelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRol)
                    .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanelRolsAndRules, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Permisos", jPanelPermissions);

        jRadioButtonWeb.setText("Web (No se requiere office para visualizar el contenido)");

        jRadioButtonOffice.setText("Office (Es requerido office para visualizar el contenido)");

        javax.swing.GroupLayout jPanelTypeOfDisplayLayout = new javax.swing.GroupLayout(jPanelTypeOfDisplay);
        jPanelTypeOfDisplay.setLayout(jPanelTypeOfDisplayLayout);
        jPanelTypeOfDisplayLayout.setHorizontalGroup(
            jPanelTypeOfDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTypeOfDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTypeOfDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonWeb)
                    .addComponent(jRadioButtonOffice))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanelTypeOfDisplayLayout.setVerticalGroup(
            jPanelTypeOfDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTypeOfDisplayLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jRadioButtonWeb)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonOffice)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tipo de despluiegue", jPanelTypeOfDisplay);

        jPanelChangePagContenido.setLayout(new javax.swing.BoxLayout(jPanelChangePagContenido, javax.swing.BoxLayout.LINE_AXIS));
        jPanelChangePagContenido.add(pagContenido1);

        jTabbedPane2.addTab("Páginación del Contenido", jPanelChangePagContenido);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                DialogContentInformation dialog = new DialogContentInformation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {

                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSchuddler;
    private javax.swing.JButton jButtonSendToAuthorize;
    private javax.swing.JCheckBox jCheckBoxAllowEditFromWeb;
    private javax.swing.JComboBox jComboBoxRol;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel1Activity;
    private javax.swing.JLabel jLabel1DateofModification;
    private javax.swing.JLabel jLabel1Description;
    private javax.swing.JLabel jLabel1DisplayDateOfModification;
    private javax.swing.JLabel jLabel1DisplayState;
    private javax.swing.JLabel jLabel1Id;
    private javax.swing.JLabel jLabel1State;
    private javax.swing.JLabel jLabel1Title;
    private javax.swing.JLabel jLabel2DisplayActivity;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelVisible;
    private javax.swing.JList jListRol;
    private javax.swing.JList jListRules;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelChangePagContenido;
    private javax.swing.JPanel jPanelInformation;
    private javax.swing.JPanel jPanelPermissions;
    private javax.swing.JPanel jPanelRol;
    private javax.swing.JPanel jPanelRolsAndRules;
    private javax.swing.JPanel jPanelRules;
    private javax.swing.JPanel jPanelTypeOfDisplay;
    private javax.swing.JRadioButton jRadioButtonOffice;
    private javax.swing.JRadioButton jRadioButtonVisibleNo;
    private javax.swing.JRadioButton jRadioButtonVisibleYes;
    private javax.swing.JRadioButton jRadioButtonWeb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldTitle;
    private org.semanticwb.openoffice.ui.wizard.PagContenido pagContenido1;
    // End of variables declaration//GEN-END:variables
}
